<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>Ritten.OpenTofu</Title>
    <Description>OpenTofu for Ritten workflows.</Description>
    <PackageTags>devops;cicd;build;automation;workflows;pipelines;opentofu;terraform;infrastructure</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Ritten.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ritten.Core\Ritten.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="all" />
  </ItemGroup>

</Project>
