<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Title>Ritten</Title>
    <Description>A command line tool for running portable CI/CD workflows.</Description>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>ritten</ToolCommandName>
    <PackageId>Ritten</PackageId>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>devops;cicd;build;automation;workflows;pipelines;deployment</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="/">
      <Link>README.md</Link>
    </None>
    <None Include="..\..\CHANGELOG.md" Pack="true" PackagePath="/">
      <Link>CHANGELOG.md</Link>
    </None>
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Ritten.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ritten.Core\Ritten.Core.csproj" />
    <ProjectReference Include="..\Ritten.DotNet\Ritten.DotNet.csproj" />
    <ProjectReference Include="..\Ritten.Git\Ritten.Git.csproj" />
    <ProjectReference Include="..\Ritten.GitHub\Ritten.GitHub.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="all" />
    <PackageReference Include="NuGet.Common" />
    <PackageReference Include="NuGet.Protocol" />
    <PackageReference Include="NuGet.Versioning" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

</Project>
